#!/bin/bash

function cache_services() {
    local SERVICE_YMLFILE=$1

    local SERVICE_URL=${OS_SERVICES_REPO}/${REPO_VERSION}
    local SERVICE_INDEX_URL="${SERVICE_URL}/index.yml"
    local SERVICE_YMLFILE_URL="${SERVICE_URL}/${SERVICE_YMLFILE}"

    local SERVICE_INDEX_URL_MD5=$(echo -n ${SERVICE_INDEX_URL}|md5sum|cut -d ' ' -f1)
    local SERVICE_YMLFILE_URL_MD5=$(echo -n ${SERVICE_YMLFILE_URL}|md5sum|cut -d ' ' -f1)

    mkdir -p ${INITRD_DIR}/usr/share/ros/services-cache/
    wget -O ${INITRD_DIR}/usr/share/ros/services-cache/${SERVICE_INDEX_URL_MD5} ${SERVICE_INDEX_URL}
    wget -O ${INITRD_DIR}/usr/share/ros/services-cache/${SERVICE_YMLFILE_URL_MD5} ${SERVICE_YMLFILE_URL}
}

echo Create initrd layout in $INITRD_DIR

rm -rf ${INITRD_DIR}
mkdir -p ${INITRD_DIR}

# Use burmilla/os-console image content as baseline for initrd
id=$(docker create burmilla/os-console)
docker cp $id:/ ${INITRD_DIR}/
docker rm -v $id

mkdir -p ${INITRD_DIR}/usr/{etc,lib,bin,share/ros}

./scripts/template
cp bin/ros                     ${INITRD_DIR}/usr/bin/

cat <<HERE > ${INITRD_DIR}/usr/share/ros/os-release
NAME="BurmillaOS"
VERSION=${VERSION}
ID=rancheros
ID_LIKE=
VERSION_ID=${VERSION}
PRETTY_NAME="BurmillaOS ${VERSION}"
HOME_URL="https://burmillaos.org"
SUPPORT_URL="https://github.com/burmilla/os"
BUG_REPORT_URL="https://github.com/burmilla/os/issues"
BUILD_ID=
HERE

pushd ${INITRD_DIR}/usr/etc
ln -s ../share/ros/os-release .
popd
